name: nixtlats
channels:
  - conda-forge
dependencies:
  - dask<2023.1.1
  - jupyterlab
  - pandas
  - plotly
  - prophet
  - pyspark>=3.3
  - pip:
    - black
    - holidays
    - nbdev
    - mypy
    - flake8
    - python-dotenv
    - statsforecast
    - utilsforecast>=0.0.13
    - requests
    - duckdb<0.8
    - fugue[ray]>=0.8.7
    - fire
    - tabulate
    - tenacity
