name: nixtlats
channels:
  - conda-forge
dependencies:
  - dask<2023.1.1
  - jupyterlab
  - pandas
  - plotly
  - pyspark>=3.3
  - pip:
    - black
    - nbdev
    - mypy
    - flake8
    - python-dotenv
    - statsforecast
    - requests
    - openbb
    - duckdb<0.8
    - fugue[ray]
    - ray<2.4
