name: autotimeseries
channels:
  - conda-forge
dependencies:
  - python=3.7
  - boto3
  - jupyterlab
  - pandas
  - pip
  - pyarrow
  - python-dotenv
  - requests
  - s3fs
  - tabulate
  - pip:
    - nbdev
