name: Deploy to docs.readme

on:
  push:
    branches: [main]
  workflow_dispatch:

defaults:
  run:
    shell: bash -l {0}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy-readme:
    runs-on: ubuntu-latest 
    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up environment
        uses: mamba-org/setup-micromamba@v1 
        with:
          environment-file: environment.yml
          create-args: python=${{ matrix.python-version }}
          cache-environment: true

      - name: Install pip requirements
        run: pip install ./ 

      - name: Install Quarto
        run: nbdev_install_quarto

      - name: Create readme docs 
        env:
          README_HOST_URL: ${{ secrets.README_HOST_URL }}
          README_CATEGORY: ${{ secrets.README_CATEGORY }}
        run: ./action_files/create_readme_docs.sh

      - name: Set up Git User
        run: |
          git config --global user.name 'FedericoGarza'
          git config --global user.email 'fede.garza.ramirez@gmail.com'

      - name: Push PNGs to readme_docs branch
        run: |
          git push origin --delete readme_docs || true
          git checkout -b readme_docs 
          git add -f "*.png"
          git commit -m "[cd] update png images" || echo "No changes to commit"
          git push --set-upstream origin readme_docs
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}

      - name: Deploy to docs.readme
        uses: readmeio/rdme@v8
        with:
          rdme: docs ./nbs/_docs/docs/ --key=${{ secrets.README_API_KEY }} --version=0.0.2
