name: "tsfeatures"

on:
  push:
    branches: [ main ]
    paths:
      - "tsfeatures/**"
      - ".github/workflows/tsfeatures.yml"
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  continuous-integration-docker-image-ecr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build docker image and push
        uses: docker/build-push-action@v2
        with:
          file: tsfeatures/Dockerfile
          tags: tsfeatures:latest
          build-args: ENV_YML=tsfeatures/environment.yml
          outputs: type=docker, dest=/tmp/dockerimage.tar

      - name: Load Docker image
        run: |
          docker load --input /tmp/dockerimage.tar
          docker image ls -a

      - name: Test scripts
        run: |
          cd tsfeatures
          make test_tsfeatures

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: dockerimage
          path: /tmp/dockerimage.tar

      - name: Upload outputs
        uses: actions/upload-artifact@v2
        with:
          name: calendar-features
          path: data/outputs/

  continuous-deployment-docker-image-ecr:
    runs-on: ubuntu-latest
    needs: [continuous-integration-docker-image-ecr]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dockerimage
          path: /tmp

      - name: Load Docker image
        run: |
          docker load --input /tmp/dockerimage.tar
          docker image ls -a

      - name: Push to ECR
        uses: jwalton/gh-ecr-push@v1
        with:
          access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_DEFAULT_REGION }}
          image: tsfeatures

  continuous-integration-lambda:
    runs-on: ubuntu-latest

    steps:
      # Step 1
      - uses: actions/checkout@v2

      # Step 2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
          architecture: x64
      # Step 3
      - name: Install Python Virtual ENV
        run: pip3 install virtualenv
      # Step 4
      - name:  Setup Virtual env
        uses: actions/cache@v2
        id: cache-venv
        with:
          path: venv
          key: ${{ runner.os }}-venv-v4-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-venv-v4-
      # Step 5
      - name: Activate and Install Depencies into Virtual env
        run: python -m venv venv && source venv/bin/activate &&
          pip3 install -r requirements.txt
        if: steps.cache-venv.outputs.cache-hit != 'true'
      # Step 6
      - name: Activate venv # and Run Test
        run: . venv/bin/activate # && pytest

      # Step 7
      - name: Create Zipfile archive of Dependencies
        run: |
          cd ./venv/lib/python3.7/site-packages
          zip -r9 ../../../../api.zip .

      # Step 8
      - name: Add App to Zip file
        run: cd ./api && zip -g ../api.zip -r .

      # Step 9
      - name: Add scripts to Zip file
        run: |
          cd ./tsfeatures && \
            zip -g ../api.zip -r .

      # Step 10
      - name: Upload zip file artifact
        uses: actions/upload-artifact@v2
        with:
          name: api
          path: api.zip

  continuous-deployment-lambda:
    runs-on: ubuntu-latest
    needs: [continuous-integration-lambda]
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Install AWS CLI
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Download Lambda api.zip
        uses: actions/download-artifact@v2
        with:
          name: api

      - name: Upload to S3
        run: aws s3 cp api.zip s3://tsfeatures-api/api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Deploy new Lambda
        run: aws lambda update-function-code --function-name tsfeatures --s3-bucket tsfeatures-api --s3-key api.zip
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
